name:                online-hoc-nyan
version:             0.1.0.0
github:              "takoeight0821/online-hoc-nyan"
license:             BSD3
author:              "Yuya Kono"
maintainer:          "takohati0821@gmail.com"
copyright:           "2019 Yuya Kono"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/online-hoc-nyan#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- QuickCheck
- servant-mock
- servant-server
- wai
- warp
- http-api-data
- process
- servant-js
- bytestring
- http-media

library:
  source-dirs: src

executables:
  online-hoc-nyan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - online-hoc-nyan

tests:
  online-hoc-nyan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - online-hoc-nyan
